FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /app
EXPOSE 5000
ENV ASPNETCORE_URLS=http://+:5000
RUN dotnet tool install --global dotnet-ef --version 8.0.0
RUN apt-get update && apt-get install -y curl gnupg \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y mssql-tools18 \
    && apt-get clean
ENV PATH="$PATH:/root/.dotnet/tools:/opt/mssql-tools18/bin"
ENTRYPOINT ["dotnet", "watch", "run"]
